# Generated by Django 3.1 on 2021-06-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModelSignals", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
